#include "stdafx.h"
#include "unity.h"
DWORD  G::MOUDLE;
DWORD  G::MOUDLE_END;
HANDLE G::hPipe;
DWORD* I::ClientMode;
DWORD* I::Client;
DWORD* I::VPanel;
DWORD* I::ModelRender;
DWORD* I::Surface;
IEngineClient* I::Engine;
